<?php ob_start();?>
<style>
    
      section {
        margin-top: 90px;
        margin-bottom: 60px;
    }
   
   a {
        color:#2d9ed9;
    }
   h3{color:#1e54a1;}

</style>
    <div class="container">
        <div class="row">
            <div class= "col-12">
            <section>
                <div class="card">
                  <!--<div class="card-header">
                    Team LLVM
                  </div>-->
                  <div class="card-body">
                    <h3 class="card-title">LLVM for Vector Extension & FIRRTL</h3>
                    <p class="card-text">
                        We are preparing to move forward after the tape-out of the SoCs. We aim to add
another extension known as the Vector Extension (short:' V') to our core. This will
accelerate our processing speed for complex machine algorithm. We hoped that a
low-level virtual machine (<a href="/llvm.php">LLVM</a>) will provide the opportunity for us to write an
inline vector extension assembly. We are forming a team that is solely exploring an
LLVM. Another work that is in progress is the optimization of CHISEL generated
Verilog which is generated by FIRRTL. Usually, the CHISEL generated Verilog is
not much readable the naming convention is not understandable by the observer so
for tackling this problem the subset of the students is working on that.

                        
                    <h5>Team Members</h5>
                    <ul class="pl-5">
                        <li><a href="/member.php?id=5">Muhammad Waleed Waseem</a></li>
                        <li>Muhammad Mohsin Siddiqui</li>
                        <li>Monis Javed</li>
                        <li><a href="/member.php?id=11">Raheel Siddiqui</a></li>
                    </ul>
                    <h5>Team Mentor</h5>
                    - Engr. Farhan Ahmed Karim
                  </div>
                </div>
                <div class="card mt-15">
                  <!--<div class="card-header">
                    Team LLVM
                  </div>-->
                  <div class="card-body">
                    <h3 class="card-title">Reverse Engineering Rocket Chip</h3>
                    <p class="card-text"><a href="re-rocketchip.php">Rocket chip</a> is the SoC generator written in Chisel and understood by quite a few.
We make our own pedagogy which enabled our undergraduate students to
understand this complex and powerful tool and its architecture which is not well
documented and is a pain problem for many industries looking to adopt Chisel and
RISC-V. Our goal is to Reverse Engineer the Rocket Chip generator by using the
expertise of Scala (functional Programming and Object Oriented Programming).
                    <h5>Team Members</h5>
                    <ul  class="pl-5">
                        <li><a href="/member.php?id=3">Uzair Khan (Team Lead)</a></li>
                        <li><a href="/member.php?id=13">Shahzaib Kashif</a></li>
                        <li><a href="/member.php?id=18">Talha Ahmed</a></li>
                        <li><a href="/member.php?id=17">Syeda Fizza Jaffery</a></li>
                        <li><a href="/member.php?id=9">Mohammad Shahzaib</a></li>
                        <li>Almas Ibrahim</li>
                        <li>Mohsin Raza</li>
                        <li>Ubab Nadeem</li>
                    </ul>
                    <h5>Team Mentor</h5>
                    - Engr. Farhan Ahmed Karim
                  </div>
                </div>
                 <div class="card mt-15">
                  <!--<div class="card-header">
                    Team LLVM
                  </div>-->
                  <div class="card-body">
                    <h3 class="card-title">Ibtida System on a Chip</h3>
                    <p class="card-text">
                        This team is working on the design of a complete System on a Chip (SoC) that is
built from scratch based on the RISC-V Instruction Set Architecture (ISA). The <a href="/ibtida.php">Ibtida ابتدا </a>project's aim is to build a completely open-source chip from scratch and take it
from designing to fabrication using all open-source tools and Process Design Kit
(PDK) made possible by Efabless, Google and FOSSI Foundation.
                    </p>
                    <!--<a href="#" class="btn btn-primary">Go somewhere</a>-->
                    <h5>Team Members</h5>
                    <ul  class="pl-5">
                        <li><a href="/member.php?id=7">Aireen Amir Jalal</a></li>
                        <li><a href="/member.php?id=6">Sajjad Ahmed Hasan</a></li>
                        <li><a href="/member.php?id=10">Usman Zain</a></li>
                        <li><a href="/member.php?id=1">Hadir Khan</a></li>
                    </ul>
                    <h5>Team Mentor</h5>
                    - Dr. Ali Ahmed
                  </div>
                </div>
                 <div class="card mt-15">
                  <!--<div class="card-header">
                    Team LLVM
                  </div>-->
                  <div class="card-body">
                    <h3 class="card-title">Team Ghazi System on Chip</h3>
                    <p class="card-text">
                        The team behind the RTL (Register Transfer Level), APR (Placement and Routing)
and both Pre and Post Synthesis Verification of <a href="ghazi.php">Ghazi</a>  System on a Chip. Uses of a
core in deeply embedded systems such as IoT end-nodes range from simple control
and interaction with peripherals, to the execution of light-weight processing, all the
way up to the computation of complex signal processing algorithms. Design of such
cores usually involves high royalty fee and copyright implications when using ARM
or Intel x86 based architecture. Thus, an SoC, that uses a core based on an open
source ISA (Instruction Set Architecture) is often required that we could easily
adapt to suit multiple specifications as needed.

                    <h5>Team Members</h5>
                    <ul  class="pl-5">
                        <li><a href="/member.php?id=2">Hamza Shabbir</a></li>
                        <li><a href="/member.php?id=12">Wajeh ul Hasan</a></li>
                        <li><a href="/member.php?id=16">Zain Rizwan Khan</a></li>
                        <li><a href="/member.php?id=4">Zeeshan Rafique</a></li>
                    </ul>
                    <h5>Team Mentor</h5>
                    - Dr. Ali Ahmed
                  </div>
                </div>
                
                 <div class="card mt-15">
                  <!--<div class="card-header">
                    Team LLVM
                  </div>-->
                  <div class="card-body">
                    <h3 class="card-title">BURQ IDE</h3>
                    <p class="card-text">
                            Verification and validation of any hardware is an essential and most important part.
                            For the verification of our SoC we have designed a tool which is known as ‘<a href="burq.php">BURQ</a>’.
                            The idea is that a core (either written in chisel or verilog) could be tested via the
                            IDE automatically without setting up custom compilers or setting paths to the test
                            file and writing scripts.
                    </p>
                     <h5>Team Mentor</h5>
                    - Engr. Farhan Ahmed Karim
                  </div>
                </div>
                
                  <div class="card mt-15">
                  <!--<div class="card-header">
                    Team LLVM
                  </div>-->
                  <div class="card-body">
                    <h3 class="card-title">Oxygen Simulator</h3>
                    <p class="card-text">
                        Oxygen is a student-focused, open-source, educational, and web-based RISC-V Instruction
                        Set Simulator. Oxygen supports I-Extension, IM-Extension and IMC-Extension together.
                        Oxygen was mainly built for education purposes so that the students who want to learn
                        about the RISC-V Instruction Set Architecture can benefit from it
                        </p>
                    <h5>Team Members</h5>
                    <ul  class="pl-5">
                        <li>Ali Hasan Ahmed Khan</li>
                        <li>Tayyab Farooq</li>
                        <li>Minhaj Ahmed</li>
                    </ul>
                    <h5>Team Mentor</h5>
                    - Dr. Ali Ahmed<br/>
                    - Engr. Farhan Ahmed Karim
                  </div>
                </div>
                
                
            </section>
     </div>
    </div>
</div>
	

<?php 
   $pagesection = ob_get_contents();
   ob_end_clean();
   $bannerimgurl = 'img/bg-img/bg-1.jpg';
   $bannerheading = 'LLVM & FIRRTL/ BURQ';
   @include('master-without-banner.php');   
?>
   